# Generated by Django 5.2.1 on 2026-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('UAH', '₴ Hryvnia'), ('USD', '$ Dollar'), ('EUR', '€ Euro')], default='USD', max_length=3),
        ),
    ]
