# Generated by Django 5.2.1 on 2026-05-24 19:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_single_transfer', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Maximum amount per single transfer', max_digits=12)),
                ('max_daily_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Maximum total withdrawal per day', max_digits=12)),
                ('max_single_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Maximum amount per single withdrawal', max_digits=12)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='wallets.wallet')),
            ],
        ),
    ]
