# Generated by Django 5.2.1 on 2026-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_transactionlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
