# Generated by Django 5.2.1 on 2026-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_virtualcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
